<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Form\HarvestForm $form
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')
    ->appendAttribute('class', 'oai-pmh-harvester oai-pmh-harvester-index');

$this->headLink()
    ->appendStylesheet($assetUrl('css/oai-pmh-harvester.css', 'OaiPmhHarvester'));
$this->headScript()
    ->appendFile($assetUrl('js/oai-pmh-harvester.js', 'OaiPmhHarvester'));
?>

<?= $this->pageTitle($translate('Harvester'), 1, $translate('OAI-PMH')) ?>

<div id="page-actions">
    <button form="harvest-repository" type="submit" class="button"><?= $translate('View sets') ?></button>
</div>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\OaiPmhHarvester')->menu() ?>
</nav>

<h3><?= $translate('Set repository to harvest') ?></h3>

<p>
<?= sprintf(
    $translate('Use this form if you want to harvest a repository only once (or occasionally) and if default mappings fit your needs. If you want to repeatedly harvest the same repository, or want better control on mappings, <a href="%s">define a new source</a>.'),
    $this->url('admin/oaipmhharvester/source', ['action' => 'add'])
); ?>
</p>

<?= $this->form($form) ?>
