<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'add oaipmhharvester-configuration');
$form->prepare();
?>

<?php echo $this->pageTitle($translate('New configuration'), 1, $translate('OAI-PMH')); ?>
<?php echo $this->trigger('view.add.before'); ?>
<?php echo $this->form()->openTag($form); ?>
<?php $this->trigger('view.add.form.before', ['form' => $form]); ?>
<div id="page-actions">
    <?= $this->hyperlink($translate('Cancel'), $this->url('admin/oaipmhharvester/configuration'), ['class' => 'button']) ?>
    <button><?php echo $translate('Add'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.add.form.after', ['form' => $form]); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.add.after'); ?>
