<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$assetUrl = $this->plugin('assetUrl');

$this->htmlElement('body')->appendAttribute('class', 'oai-pmh-harvester oai-pmh-harvester-configuration browse');

$this->headLink()->appendStylesheet($assetUrl('css/oai-pmh-harvester.css', 'OaiPmhHarvester'));
$this->headScript()->appendFile($assetUrl('js/oai-pmh-harvester.js', 'OaiPmhHarvester'));
?>

<?= $this->pageTitle($translate('Configurations'), 1, $translate('OAI-PMH')) ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->browse()->renderSortSelector('oaipmhharvester_configurations'); ?>
</div>

<div id="page-actions">
    <?php if ($this->userIsAllowed('OaiPmhHarvester\Api\Adapter\ConfigurationAdapter', 'create')): ?>
    <?php echo $this->hyperlink($translate('Add new configuration'), $this->url(null, ['action' => 'add'], true), ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php if ($configurations): ?>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $translate('Name'); ?></th>
            <th><?php echo $translate('Converter'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($configurations as $configuration): ?>
        <tr>
            <td>
                <?= $configuration->link($configuration->name()) ?>
                <ul class="actions">
                    <?php $this->trigger('view.browse.actions', ['resource' => $configuration]); ?>
                    <?php if ($configuration->userIsAllowed('update')): ?>
                        <li><?php echo $configuration->link('', 'edit', [
                            'class' => 'o-icon-edit',
                            'title' => $translate('Edit'),
                        ]); ?></li>
                    <?php endif; ?>
                    <?php if ($this->userIsAllowed('OaiPmhHarvester\Api\Adapter\ConfigurationAdapter', 'create')): ?>
                        <li><?php echo $configuration->link('', 'duplicate', [
                            'class' => 'o-icon- fa-copy',
                            'title' => $translate('Duplicate'),
                        ]); ?></li>
                    <?php endif; ?>
                    <?php if ($configuration->userIsAllowed('delete')): ?>
                        <li><?php echo $this->hyperlink('', '#', [
                            'data-sidebar-selector' => '#sidebar',
                            'data-sidebar-content-url' => $configuration->url('delete-confirm'),
                            'class' => 'o-icon-delete sidebar-content',
                            'title' => $translate('Delete'),
                        ]); ?></li>
                    <?php endif; ?>
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $configuration->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?= $configuration->converterName() ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="sidebar" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $translate('Omeka could not find any configurations.'); ?></p>
</div>

<?php endif; ?>
