<?php
$translate = $this->plugin('translate');
?>
<h3>
    <a href="<?php echo $this->escapeHtml($resource->url()); ?>"><?php echo $this->escapeHtml($resource->name()); ?></a>
</h3>

<div class="meta-group">
    <h4><?php echo $translate('Converter'); ?></h4>
    <div class="value"><?= $resource->converterName() ?></div>
</div>

<?php $converter = $resource->converter(); ?>
<?php if ($converter instanceof \OaiPmhHarvester\Converter\ConfigurableConverterInterface): ?>
    <?= $resource->converter()->getConfigurationDetails($this, $resource->settings()) ?>
<?php endif; ?>

<?php $this->trigger('view.details', array('entity' => $resource)); ?>
