<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Api\Representation\ConfigurationRepresentation|null $configuration
 */
?>
<?php if ($configuration): ?>
    <?php $settings = $configuration->settings(); ?>
    <?php $fields = $settings['mappings'] ?? [] ?>
    <?php foreach ($fields as $fieldData): ?>
        <?= $this->partial('oai-pmh-harvester/admin/mappings/field-row', ['fieldData' => $fieldData, 'configuration' => $configuration]) ?>
    <?php endforeach; ?>
<?php endif; ?>
