<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'edit oaipmhharvester-source');
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Edit source'), 1, $translate('OAI-PMH')); ?>
<?php echo $this->trigger('view.edit.before'); ?>
<?php echo $this->form()->openTag($form); ?>
<?php $this->trigger('view.edit.form.before', ['form' => $form]); ?>
<div id="page-actions">
    <?= $this->hyperlink($translate('Cancel'), $this->url('admin/oaipmhharvester/source'), ['class' => 'button']) ?>
    <button><?php echo $translate('Save changes'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.edit.form.after', ['form' => $form]); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.edit.after'); ?>
