<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'harvest oaipmhharvester-source');
$form->prepare();
?>

<?php echo $this->pageTitle($source->name(), 1, $translate('OAI-PMH'), $translate('Harvest')); ?>
<?php echo $this->trigger('view.harvest.before'); ?>
<?php echo $this->form()->openTag($form); ?>
<?php $this->trigger('view.harvest.form.before', ['form' => $form]); ?>
<div id="page-actions">
    <?= $this->hyperlink($translate('Cancel'), $this->url('admin/oaipmhharvester/source'), ['class' => 'button']) ?>
    <button><?php echo $translate('Start harvest'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.harvest.form.after', ['form' => $form]); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.harvest.after'); ?>
