<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Laminas\Form\Element $element
 */
?>
<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/mapping.css', 'OaiPmhHarvester'));
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/fields-form.js', 'OaiPmhHarvester'));
?>
<div class="fields-form-element"
    data-field-list-url="<?php echo $this->escapeHtml($element->getOption('field_list_url')); ?>"
    data-field-row-url="<?php echo $this->escapeHtml($element->getOption('field_row_url')); ?>"
    data-field-edit-sidebar-url="<?php echo $this->escapeHtml($element->getOption('field_edit_sidebar_url')); ?>">
    <?php $element->setValue(''); ?>
    <?php echo $this->formHidden($element); ?>
    <fieldset class="field-add-group">
        <button 
            type="button" 
            class="fields-field-add-button o-icon-add" 
            aria-label="<?php echo $this->translate('Add Rule'); ?>" 
            title="<?php echo $this->translate('Add Rule'); ?>"
        > 
            Add rule 
        </button>
    </fieldset>
    <ul class="fields-fields"></ul>
</div>
