<dl>
    <?php $namespaces = $settings['namespaces'] ?? [] ?>
    <?php if ($namespaces): ?>
        <div class="property">
            <dt><?= $this->translate('XML namespaces') ?></dt>
            <dd>
                <table class="tablesaw">
                    <thead>
                        <tr>
                            <th><?= $this->translate('Prefix') ?></th>
                            <th><?= $this->translate('URI') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($namespaces as $prefix => $uri): ?>
                            <tr>
                                <td><?= $this->escapeHtml($prefix) ?></td>
                                <td><?= $this->escapeHtml($uri) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </dd>
        </div>
    <?php endif; ?>

    <?php $mappings = $settings['mappings'] ?? [] ?>
    <?php if ($mappings): ?>
        <div class="property">
            <dt><?= $this->translate('Mappings') ?></dt>
            <dd>
                <table class="tablesaw">
                    <thead>
                        <tr>
                            <th><?= $this->translate('Mapping') ?></th>
                            <th><?= $this->translate('XPath') ?></th>
                            <th><?= $this->translate('Property') ?></th>
                            <th><?= $this->translate('Type') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($mappings as $mapping): ?>
                            <?php
                                $label = '';
                                switch ($mapping['name']) {
                                    case 'xpath':
                                        $label = $this->translate('Query value');
                                        break;
                                    case 'literal-value-xpath-condition':
                                        $label = $this->translate('Create value');
                                        break;
                                    default:
                                        $label = '';
                                }

                                $typeLabel = $this->dataType()->getLabel($mapping['type'] ?? 'literal'); 
                                if (str_starts_with($mapping['type'], 'customvocab')) {
                                    $typeLabel = 'CusomVocab - ' . $typeLabel;
                                }
                            ?>
                            <tr>
                                <td><?= $label ?></td>
                                <td><?= $this->escapeHtml($mapping['xpath'] ?? '') ?></td>
                                <td><?= $this->escapeHtml($mapping['property'] ?? '') ?></td>
                                <td><?= $this->escapeHtml($this->translate($typeLabel)) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </dd>
        </div>
    <?php endif; ?>
</dl>
