<?php $this->headLink()->appendStylesheet($this->assetUrl('css/mapping.css', 'OaiPmhHarvester')); ?>
<dl>
    <?php $namespaces = $settings['namespaces'] ?? [] ?>
    <?php if ($namespaces): ?>
        <div class="property">
            <dt><?= $this->translate('XML namespaces') ?></dt>
            <dd>
                <table class="tablesaw">
                    <thead>
                        <tr>
                            <th><?= $this->translate('Prefix') ?></th>
                            <th><?= $this->translate('URI') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($namespaces as $prefix => $uri): ?>
                            <tr>
                                <td><?= $this->escapeHtml($prefix) ?></td>
                                <td><?= $this->escapeHtml($uri) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </dd>
        </div>
    <?php endif; ?>

    <?php $mappings = $settings['mappings'] ?? [] ?>
    <?php if ($mappings): ?>
        <div class="property">
            <dt><?= $this->translate('Mapping Rules') ?></dt>
            <dd class="fields-field row">
                <?php foreach ($mappings as $mapping): ?>
                    <?php
                    $typeLabel = '';
                    $property = $mapping['property'];
                    if ($mapping['type']) {
                        $typeLabel = $this->dataType()->getLabel($mapping['type'] ?? 'literal');
                        if (str_starts_with($mapping['type'], 'customvocab')) {
                            $typeLabel = 'CusomVocab - ' . $typeLabel;
                        }
                    }
                    ?>
                    <div class="fields-field-summary row ">
                        <span class="fields-field-name">Rule </span>
                        <span class="fields-field-term">
                            <?= $this->escapeHtml($property) ?> (<?= $this->escapeHtml($this->translate($typeLabel)) ?>) 
                        </span> 
                    </div>
                    <?= $this->partial('oai-pmh-harvester/admin/mappings/rule', ['rule' => $mapping]) ?>
                <?php endforeach; ?>
            </dd>
        </div>
    <?php endif; ?>
</dl>
